name: Check Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install Visual Studio Build Tools
      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2019buildtools --package-parameters "--allWorkloads --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -y

      # Build check.c using the Visual Studio compiler
      - name: Build check.c
        run: MSBuild.exe check/check/check.vcxproj /p:Configuration=Release

      # Copy executables to the root of the repository
      - name: Copy executables to root of repository
        run: |
          cp check/check/Release/check.exe ./executables/
        working-directory: ${{ github.workspace }}
