name: Compile check.c using Visual Studio Compiler
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSVC compiler environment
      uses: microsoft/setup-msvc@v1.6.2
    - name: Build check.c
      run: |
        cd check/check
        msbuild /p:Configuration=Release check.vcxproj
