name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust and Cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build main.rs using Cargo
      - run: cargo build --release

      # Install Visual Studio Build Tools
      - name: Install Visual Studio Build Tools
        run: choco install windows-sdk-10-version-10.0.19041.0-buildtools -y

      # Build check.c using the Visual Studio compiler
      - name: Build check.c
        run: MSBuild.exe check/check/check.vcxproj /p:Configuration=Release

      # Copy executables to the root of the repository
      - name: Copy executables to root of repository
        run: |
          cp wallpaper/target/release/main.exe ./executables/
          cp check/check/Release/check.exe ./executables/
        working-directory: ${{ github.workspace }}