name: Check if wallpaper compiles

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Install Rust and Cargo
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build main.rs using Cargo
      - name: Build main.rs
        run: cargo build --release
        working-directory: wallpaper
